version: '3.3'

services:
  backend:
    image: '{{projectName}}'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    command: npm run start:dev